name: dishai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Projemiz için eklediğimiz paketler
  tflite_flutter: ^0.11.0
  image_picker: ^1.0.7
  supabase_flutter: ^2.5.0
  path_provider: ^2.1.2
  image: ^4.1.7

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/